import { parseDigestId, parseEntityId, type ControlEventId, type DeviceId, type InvitationId, type KeyEpochId, type ProjectId } from "../identities.ts";
import { expectBytes, expectEnum, expectExactRecord, expectLiteral, freezeRecord } from "../validation.ts";
import { parseEnrollmentBatchMarker, parseInvitationEvidenceCore, parsePossessionChallengeEnvelope, type EnrollmentBatchMarker, type InvitationEvidenceCore, type PossessionChallengeEnvelope } from "./enrollment-contracts.ts";
import { parseHc2DigestId, type EnrollmentCeremonyId, type EpochDeliveryId, type MembershipTransitionId } from "./identities.ts";
import { parseWrappedLocalEpochRecord, type WrappedLocalEpochRecord } from "./epoch-custody.ts";

export type StoredInvitationStatus = "accepted" | "cancelled" | "consumed";
export type StoredInvitation = Readonly<{
  schema_version: 1;
  record_kind: "stored_invitation";
  invitation_id: InvitationId;
  evidence: InvitationEvidenceCore;
  status: StoredInvitationStatus;
  terminal_control_event_id: ControlEventId | null;
  consumed_transition_id: MembershipTransitionId | null;
}>;

export type StoredPossessionChallenge = Readonly<{
  schema_version: 1;
  record_kind: "stored_possession_challenge";
  project_id: ProjectId;
  challenge: PossessionChallengeEnvelope;
  expected_response_sha256: Uint8Array;
  status: "pending" | "consumed" | "replaced" | "cancelled";
  consumed_proof_id: string | null;
}>;

export const enrollmentTransitionPhases = [
  "planned",
  "control_reserved",
  "epoch_wrapped",
  "delivery_partial",
  "delivery_complete",
  "control_committed",
  "batch_visible",
  "indexeddb_finalized",
  "reopen_verified",
  "admission_ready",
  "complete"
] as const;
export type EnrollmentTransitionPhase = (typeof enrollmentTransitionPhases)[number];

export type JournaledEpochDelivery = Readonly<{
  delivery_id: EpochDeliveryId;
  exact_bytes: Uint8Array;
}>;

export type EnrollmentTransitionJournal = Readonly<{
  schema_version: 1;
  record_kind: "enrollment_transition_journal";
  ceremony_id: EnrollmentCeremonyId;
  plan_sha256: Uint8Array;
  project_id: ProjectId;
  authorizing_device_id: DeviceId;
  previous_control_head_id: ControlEventId;
  replacement_epoch_id: KeyEpochId;
  phase: EnrollmentTransitionPhase;
  wrapped_epoch: WrappedLocalEpochRecord | null;
  transition_id: MembershipTransitionId | null;
  accepted_control_event_id: ControlEventId | null;
  journaled_deliveries: readonly JournaledEpochDelivery[];
  batch_marker: EnrollmentBatchMarker | null;
}>;

export type EnrollmentLocalCompletionMarker = Readonly<{
  schema_version: 1;
  record_kind: "enrollment_transition_completion_marker";
  ceremony_id: EnrollmentCeremonyId;
  project_id: ProjectId;
  accepted_control_event_id: ControlEventId;
  transition_id: MembershipTransitionId;
  batch_id: EnrollmentBatchMarker["batch_id"];
  completion: "verified_reopen_complete";
}>;

export interface Hc2EnrollmentStore {
  putInvitation(value: StoredInvitation): Promise<"stored" | "exact_retry">;
  readInvitation(projectId: ProjectId, invitationId: InvitationId): Promise<StoredInvitation | null>;
  cancelInvitation(projectId: ProjectId, invitationId: InvitationId, expectedStatus: "accepted", controlEventId: ControlEventId): Promise<StoredInvitation>;
  consumeInvitation(projectId: ProjectId, invitationId: InvitationId, expectedStatus: "accepted", controlEventId: ControlEventId, transitionId: MembershipTransitionId): Promise<StoredInvitation>;
  putChallenge(value: StoredPossessionChallenge): Promise<"stored" | "exact_retry">;
  readChallenge(projectId: ProjectId, challengeId: StoredPossessionChallenge["challenge"]["challenge_id"]): Promise<StoredPossessionChallenge | null>;
  consumeChallenge(projectId: ProjectId, challengeId: StoredPossessionChallenge["challenge"]["challenge_id"], proofId: string, expectedControlHeadId: ControlEventId): Promise<StoredPossessionChallenge>;
  beginTransition(value: EnrollmentTransitionJournal): Promise<Readonly<{ status: "created" | "exact_retry"; journal: EnrollmentTransitionJournal }>>;
  readTransition(projectId: ProjectId, ceremonyId: EnrollmentCeremonyId): Promise<EnrollmentTransitionJournal | null>;
  advanceTransition(expectedPhase: EnrollmentTransitionPhase, next: EnrollmentTransitionJournal): Promise<EnrollmentTransitionJournal>;
  writeCompletionMarker(value: EnrollmentLocalCompletionMarker): Promise<void>;
  readCompletionMarker(projectId: ProjectId, ceremonyId: EnrollmentCeremonyId): Promise<EnrollmentLocalCompletionMarker | null>;
}

export class Hc2InMemoryEnrollmentStore implements Hc2EnrollmentStore {
  readonly #invitations = new Map<string, StoredInvitation>(); readonly #challenges = new Map<string, StoredPossessionChallenge>(); readonly #journals = new Map<string, EnrollmentTransitionJournal>(); readonly #completion = new Map<string, EnrollmentLocalCompletionMarker>();
  async putInvitation(value: StoredInvitation): Promise<"stored" | "exact_retry"> { const record = parseStoredInvitation(value); const key = invitationKey(record.evidence.project_id, record.invitation_id); const existing = this.#invitations.get(key); if (existing) { if (!sameInvitation(existing, record)) throw new Error("A different invitation already occupies this identity."); return "exact_retry"; } this.#invitations.set(key, record); return "stored"; }
  async readInvitation(projectId: ProjectId, invitationId: InvitationId): Promise<StoredInvitation | null> { const value = this.#invitations.get(invitationKey(projectId, invitationId)); return value ? parseStoredInvitation(value) : null; }
  async cancelInvitation(projectId: ProjectId, invitationId: InvitationId, expectedStatus: "accepted", controlEventId: ControlEventId): Promise<StoredInvitation> { return this.#transitionInvitation(projectId, invitationId, expectedStatus, controlEventId, null, "cancelled"); }
  async consumeInvitation(projectId: ProjectId, invitationId: InvitationId, expectedStatus: "accepted", controlEventId: ControlEventId, transitionId: MembershipTransitionId): Promise<StoredInvitation> { return this.#transitionInvitation(projectId, invitationId, expectedStatus, controlEventId, transitionId, "consumed"); }
  #transitionInvitation(projectId: ProjectId, invitationId: InvitationId, expected: StoredInvitationStatus, eventId: ControlEventId, transitionId: MembershipTransitionId | null, status: "cancelled" | "consumed"): StoredInvitation { const key = invitationKey(projectId, invitationId); const current = this.#invitations.get(key); if (!current) throw new Error("Invitation is missing."); if (current.status === status && current.terminal_control_event_id === eventId && current.consumed_transition_id === transitionId) return parseStoredInvitation(current); if (current.status !== expected) throw new Error("Invitation CAS failed; it is already terminal."); const next = parseStoredInvitation({ ...current, status, terminal_control_event_id: eventId, consumed_transition_id: transitionId }); this.#invitations.set(key, next); return next; }
  async putChallenge(value: StoredPossessionChallenge): Promise<"stored" | "exact_retry"> { const record = parseStoredPossessionChallenge(value); const key = challengeKey(record.project_id, record.challenge.challenge_id); const existing = this.#challenges.get(key); if (existing) { if (!sameChallenge(existing, record)) throw new Error("A different possession challenge already occupies this identity."); return "exact_retry"; } this.#challenges.set(key, record); return "stored"; }
  async readChallenge(projectId: ProjectId, challengeId: StoredPossessionChallenge["challenge"]["challenge_id"]): Promise<StoredPossessionChallenge | null> { const value = this.#challenges.get(challengeKey(projectId, challengeId)); return value ? parseStoredPossessionChallenge(value) : null; }
  async consumeChallenge(projectId: ProjectId, challengeId: StoredPossessionChallenge["challenge"]["challenge_id"], proofId: string, expectedControlHeadId: ControlEventId): Promise<StoredPossessionChallenge> { const key = challengeKey(projectId, challengeId); const current = this.#challenges.get(key); if (!current) throw new Error("Possession challenge is missing."); const parsedProof = safeProofId(proofId); const head = parseDigestId("control-event", expectedControlHeadId); if (current.status === "consumed" && current.consumed_proof_id === parsedProof) return parseStoredPossessionChallenge(current); if (current.status !== "pending" || current.challenge.header_core.bound_control_head_id !== head) throw new Error("Possession challenge CAS or control-head binding failed."); const next = parseStoredPossessionChallenge({ ...current, status: "consumed", consumed_proof_id: parsedProof }); this.#challenges.set(key, next); return next; }
  async beginTransition(value: EnrollmentTransitionJournal): Promise<Readonly<{ status: "created" | "exact_retry"; journal: EnrollmentTransitionJournal }>> { const journal = parseEnrollmentTransitionJournal(value); const key = ceremonyKey(journal.project_id, journal.ceremony_id); const existing = this.#journals.get(key); if (existing) { if (!samePlan(existing, journal)) throw new Error("A different transition occupies this ceremony identity."); return Object.freeze({ status: "exact_retry", journal: parseEnrollmentTransitionJournal(existing) }); } if (journal.phase !== "planned") throw new Error("New transition journal must begin at planned."); this.#journals.set(key, journal); return Object.freeze({ status: "created", journal }); }
  async readTransition(projectId: ProjectId, ceremonyId: EnrollmentCeremonyId): Promise<EnrollmentTransitionJournal | null> { const value = this.#journals.get(ceremonyKey(projectId, ceremonyId)); return value ? parseEnrollmentTransitionJournal(value) : null; }
  async advanceTransition(expectedPhase: EnrollmentTransitionPhase, nextValue: EnrollmentTransitionJournal): Promise<EnrollmentTransitionJournal> { const next = parseEnrollmentTransitionJournal(nextValue); const key = ceremonyKey(next.project_id, next.ceremony_id); const current = this.#journals.get(key); if (!current || current.phase !== expectedPhase || !samePlan(current, next) || !validAdvance(expectedPhase, next.phase)) throw new Error("Enrollment transition journal CAS failed."); assertJournalMonotonic(current, next); this.#journals.set(key, next); return next; }
  async writeCompletionMarker(value: EnrollmentLocalCompletionMarker): Promise<void> { const marker = parseEnrollmentLocalCompletionMarker(value); const key = ceremonyKey(marker.project_id, marker.ceremony_id); const journal = this.#journals.get(key); if (!journal || journal.phase !== "complete" || journal.accepted_control_event_id !== marker.accepted_control_event_id || journal.transition_id !== marker.transition_id || journal.batch_marker?.batch_id !== marker.batch_id) throw new Error("Completion marker requires the exact complete transition journal."); const existing = this.#completion.get(key); if (existing && !sameCompletion(existing, marker)) throw new Error("Conflicting transition completion marker."); this.#completion.set(key, marker); }
  async readCompletionMarker(projectId: ProjectId, ceremonyId: EnrollmentCeremonyId): Promise<EnrollmentLocalCompletionMarker | null> { const value = this.#completion.get(ceremonyKey(projectId, ceremonyId)); return value ? parseEnrollmentLocalCompletionMarker(value) : null; }
}

const enrollmentStoreVersion = 1; const storeNames = Object.freeze({ invitations: "invitations", challenges: "possession_challenges", journals: "enrollment_transition_journals", completion: "enrollment_completion_markers" });
export const hc2EnrollmentDatabaseSchema = Object.freeze({ version: enrollmentStoreVersion, stores: Object.freeze(Object.values(storeNames).sort()) });

export class Hc2IndexedDbEnrollmentStore implements Hc2EnrollmentStore {
  readonly #factory: IDBFactory; readonly #name: string; #database: IDBDatabase | null = null;
  constructor(input: Readonly<{ indexed_db: IDBFactory; database_name: string }>) { if (!input?.indexed_db || typeof input.database_name !== "string" || !input.database_name || input.database_name.includes("\u0000")) throw new Error("Enrollment IndexedDB requires an injected factory and explicit name."); this.#factory = input.indexed_db; this.#name = input.database_name; }
  async open(): Promise<void> { if (this.#database) return; this.#database = await new Promise<IDBDatabase>((resolve, reject) => { const request = this.#factory.open(this.#name, enrollmentStoreVersion); request.onupgradeneeded = () => { for (const name of Object.values(storeNames)) if (!request.result.objectStoreNames.contains(name)) request.result.createObjectStore(name); }; request.onerror = () => reject(request.error ?? new Error("Enrollment IndexedDB open failed.")); request.onsuccess = () => resolve(request.result); }); this.#database.onversionchange = () => this.close(); }
  close(): void { this.#database?.close(); this.#database = null; }
  async putInvitation(value: StoredInvitation): Promise<"stored" | "exact_retry"> { const record = parseStoredInvitation(value); return this.#putExact(storeNames.invitations, invitationKey(record.evidence.project_id, record.invitation_id), record, parseStoredInvitation, sameInvitation); }
  async readInvitation(projectId: ProjectId, invitationId: InvitationId): Promise<StoredInvitation | null> { return this.#read(storeNames.invitations, invitationKey(projectId, invitationId), parseStoredInvitation); }
  async cancelInvitation(projectId: ProjectId, invitationId: InvitationId, expectedStatus: "accepted", controlEventId: ControlEventId): Promise<StoredInvitation> { return this.#transitionInvitation(projectId, invitationId, expectedStatus, controlEventId, null, "cancelled"); }
  async consumeInvitation(projectId: ProjectId, invitationId: InvitationId, expectedStatus: "accepted", controlEventId: ControlEventId, transitionId: MembershipTransitionId): Promise<StoredInvitation> { return this.#transitionInvitation(projectId, invitationId, expectedStatus, controlEventId, transitionId, "consumed"); }
  async #transitionInvitation(projectId: ProjectId, invitationId: InvitationId, expected: StoredInvitationStatus, eventId: ControlEventId, transitionId: MembershipTransitionId | null, status: "cancelled" | "consumed"): Promise<StoredInvitation> { const key = invitationKey(projectId, invitationId); const transaction = strictTransaction(this.#require(), [storeNames.invitations], "readwrite"); const store = transaction.objectStore(storeNames.invitations); const raw = await requestValue<unknown>(store.get(key)); if (raw === undefined) { transaction.abort(); throw new Error("Invitation is missing."); } const current = parseStoredInvitation(raw); if (current.status === status && current.terminal_control_event_id === eventId && current.consumed_transition_id === transitionId) { await transactionDone(transaction); return current; } if (current.status !== expected) { transaction.abort(); throw new Error("Invitation CAS failed; it is already terminal."); } const next = parseStoredInvitation({ ...current, status, terminal_control_event_id: eventId, consumed_transition_id: transitionId }); store.put(next, key); await transactionDone(transaction); return next; }
  async putChallenge(value: StoredPossessionChallenge): Promise<"stored" | "exact_retry"> { const record = parseStoredPossessionChallenge(value); return this.#putExact(storeNames.challenges, challengeKey(record.project_id, record.challenge.challenge_id), record, parseStoredPossessionChallenge, sameChallenge); }
  async readChallenge(projectId: ProjectId, challengeId: StoredPossessionChallenge["challenge"]["challenge_id"]): Promise<StoredPossessionChallenge | null> { return this.#read(storeNames.challenges, challengeKey(projectId, challengeId), parseStoredPossessionChallenge); }
  async consumeChallenge(projectId: ProjectId, challengeId: StoredPossessionChallenge["challenge"]["challenge_id"], proofId: string, expectedControlHeadId: ControlEventId): Promise<StoredPossessionChallenge> { const key = challengeKey(projectId, challengeId); const transaction = strictTransaction(this.#require(), [storeNames.challenges], "readwrite"); const store = transaction.objectStore(storeNames.challenges); const raw = await requestValue<unknown>(store.get(key)); if (raw === undefined) { transaction.abort(); throw new Error("Possession challenge is missing."); } const current = parseStoredPossessionChallenge(raw); const proof = safeProofId(proofId); const head = parseDigestId("control-event", expectedControlHeadId); if (current.status === "consumed" && current.consumed_proof_id === proof) { await transactionDone(transaction); return current; } if (current.status !== "pending" || current.challenge.header_core.bound_control_head_id !== head) { transaction.abort(); throw new Error("Possession challenge CAS or control-head binding failed."); } const next = parseStoredPossessionChallenge({ ...current, status: "consumed", consumed_proof_id: proof }); store.put(next, key); await transactionDone(transaction); return next; }
  async beginTransition(value: EnrollmentTransitionJournal): Promise<Readonly<{ status: "created" | "exact_retry"; journal: EnrollmentTransitionJournal }>> { const journal = parseEnrollmentTransitionJournal(value); if (journal.phase !== "planned") throw new Error("New transition journal must begin at planned."); const status = await this.#putExact(storeNames.journals, ceremonyKey(journal.project_id, journal.ceremony_id), journal, parseEnrollmentTransitionJournal, samePlan); return Object.freeze({ status: status === "stored" ? "created" : "exact_retry", journal: status === "stored" ? journal : requiredValue(await this.readTransition(journal.project_id, journal.ceremony_id)) }); }
  async readTransition(projectId: ProjectId, ceremonyId: EnrollmentCeremonyId): Promise<EnrollmentTransitionJournal | null> { return this.#read(storeNames.journals, ceremonyKey(projectId, ceremonyId), parseEnrollmentTransitionJournal); }
  async advanceTransition(expectedPhase: EnrollmentTransitionPhase, nextValue: EnrollmentTransitionJournal): Promise<EnrollmentTransitionJournal> { const next = parseEnrollmentTransitionJournal(nextValue); const key = ceremonyKey(next.project_id, next.ceremony_id); const transaction = strictTransaction(this.#require(), [storeNames.journals], "readwrite"); const store = transaction.objectStore(storeNames.journals); const raw = await requestValue<unknown>(store.get(key)); if (raw === undefined) { transaction.abort(); throw new Error("Enrollment transition journal is missing."); } const current = parseEnrollmentTransitionJournal(raw); if (current.phase !== expectedPhase || !samePlan(current, next) || !validAdvance(expectedPhase, next.phase)) { transaction.abort(); throw new Error("Enrollment transition journal CAS failed."); } assertJournalMonotonic(current, next); store.put(next, key); await transactionDone(transaction); return next; }
  async writeCompletionMarker(value: EnrollmentLocalCompletionMarker): Promise<void> { const marker = parseEnrollmentLocalCompletionMarker(value); const key = ceremonyKey(marker.project_id, marker.ceremony_id); const transaction = strictTransaction(this.#require(), [storeNames.journals, storeNames.completion], "readwrite"); const raw = await requestValue<unknown>(transaction.objectStore(storeNames.journals).get(key)); if (raw === undefined) { transaction.abort(); throw new Error("Completion transition journal is missing."); } const journal = parseEnrollmentTransitionJournal(raw); if (journal.phase !== "complete" || journal.accepted_control_event_id !== marker.accepted_control_event_id || journal.transition_id !== marker.transition_id || journal.batch_marker?.batch_id !== marker.batch_id) { transaction.abort(); throw new Error("Completion marker requires the exact complete transition journal."); } const store = transaction.objectStore(storeNames.completion); const existingRaw = await requestValue<unknown>(store.get(key)); if (existingRaw !== undefined && !sameCompletion(parseEnrollmentLocalCompletionMarker(existingRaw), marker)) { transaction.abort(); throw new Error("Conflicting transition completion marker."); } store.put(marker, key); await transactionDone(transaction); }
  async readCompletionMarker(projectId: ProjectId, ceremonyId: EnrollmentCeremonyId): Promise<EnrollmentLocalCompletionMarker | null> { return this.#read(storeNames.completion, ceremonyKey(projectId, ceremonyId), parseEnrollmentLocalCompletionMarker); }
  async #putExact<T>(storeName: string, key: IDBValidKey, value: T, parse: (value: unknown) => T, same: (left: T, right: T) => boolean): Promise<"stored" | "exact_retry"> { const parsed = parse(value); const transaction = strictTransaction(this.#require(), [storeName], "readwrite"); const store = transaction.objectStore(storeName); const raw = await requestValue<unknown>(store.get(key)); if (raw !== undefined) { if (!same(parse(raw), parsed)) { transaction.abort(); throw new Error("IndexedDB exact retry conflicts with stored evidence."); } await transactionDone(transaction); return "exact_retry"; } store.add(parsed, key); await transactionDone(transaction); return "stored"; }
  async #read<T>(storeName: string, key: IDBValidKey, parse: (value: unknown) => T): Promise<T | null> { const transaction = strictTransaction(this.#require(), [storeName], "readonly"); const raw = await requestValue<unknown>(transaction.objectStore(storeName).get(key)); await transactionDone(transaction); return raw === undefined ? null : parse(raw); }
  #require(): IDBDatabase { if (!this.#database) throw new Error("Enrollment IndexedDB must be opened explicitly."); return this.#database; }
}

export function parseStoredInvitation(value: unknown): StoredInvitation { const record = expectExactRecord(value, "stored invitation", ["schema_version", "record_kind", "invitation_id", "evidence", "status", "terminal_control_event_id", "consumed_transition_id"]); const evidence = parseInvitationEvidenceCore(record.evidence); const invitation = parseEntityId("invitation", record.invitation_id); if (evidence.invitation_id !== invitation) throw new Error("Stored invitation identity differs from evidence."); const status = expectEnum(record.status, ["accepted", "cancelled", "consumed"] as const, "stored invitation status"); const terminal = record.terminal_control_event_id === null ? null : parseDigestId("control-event", record.terminal_control_event_id); const transition = record.consumed_transition_id === null ? null : parseHc2DigestId("membership-transition", record.consumed_transition_id); if ((status === "accepted") !== (terminal === null && transition === null) || (status === "cancelled" && transition !== null) || (status === "consumed" && transition === null)) throw new Error("Stored invitation terminal evidence is inconsistent."); return freezeRecord({ schema_version: expectLiteral(record.schema_version, 1, "stored invitation version"), record_kind: expectLiteral(record.record_kind, "stored_invitation", "stored invitation kind"), invitation_id: invitation, evidence, status, terminal_control_event_id: terminal, consumed_transition_id: transition }); }
export function parseStoredPossessionChallenge(value: unknown): StoredPossessionChallenge { const record = expectExactRecord(value, "stored possession challenge", ["schema_version", "record_kind", "project_id", "challenge", "expected_response_sha256", "status", "consumed_proof_id"]); const project = parseEntityId("project", record.project_id); const challenge = parsePossessionChallengeEnvelope(record.challenge); if (challenge.header_core.project_id !== project) throw new Error("Stored challenge belongs to another project."); const response = exactDigest(record.expected_response_sha256, "expected challenge response"); const status = expectEnum(record.status, ["pending", "consumed", "replaced", "cancelled"] as const, "challenge status"); const proof = record.consumed_proof_id === null ? null : safeProofId(record.consumed_proof_id); if ((status === "consumed") !== (proof !== null)) throw new Error("Challenge consumption evidence is inconsistent."); return freezeRecord({ schema_version: expectLiteral(record.schema_version, 1, "stored challenge version"), record_kind: expectLiteral(record.record_kind, "stored_possession_challenge", "stored challenge kind"), project_id: project, challenge, expected_response_sha256: response, status, consumed_proof_id: proof }); }
export function parseEnrollmentTransitionJournal(value: unknown): EnrollmentTransitionJournal { const record = expectExactRecord(value, "enrollment transition journal", ["schema_version", "record_kind", "ceremony_id", "plan_sha256", "project_id", "authorizing_device_id", "previous_control_head_id", "replacement_epoch_id", "phase", "wrapped_epoch", "transition_id", "accepted_control_event_id", "journaled_deliveries", "batch_marker"]); const deliveries = parseDeliveries(record.journaled_deliveries); return freezeRecord({ schema_version: expectLiteral(record.schema_version, 1, "transition journal version"), record_kind: expectLiteral(record.record_kind, "enrollment_transition_journal", "transition journal kind"), ceremony_id: parseHc2DigestId("enrollment-ceremony", record.ceremony_id), plan_sha256: exactDigest(record.plan_sha256, "transition plan digest"), project_id: parseEntityId("project", record.project_id), authorizing_device_id: parseEntityId("device", record.authorizing_device_id), previous_control_head_id: parseDigestId("control-event", record.previous_control_head_id), replacement_epoch_id: parseEntityId("key-epoch", record.replacement_epoch_id), phase: expectEnum(record.phase, enrollmentTransitionPhases, "transition phase"), wrapped_epoch: record.wrapped_epoch === null ? null : parseWrappedLocalEpochRecord(record.wrapped_epoch), transition_id: record.transition_id === null ? null : parseHc2DigestId("membership-transition", record.transition_id), accepted_control_event_id: record.accepted_control_event_id === null ? null : parseDigestId("control-event", record.accepted_control_event_id), journaled_deliveries: deliveries, batch_marker: record.batch_marker === null ? null : parseEnrollmentBatchMarker(record.batch_marker) }); }
export function parseEnrollmentLocalCompletionMarker(value: unknown): EnrollmentLocalCompletionMarker { const record = expectExactRecord(value, "enrollment transition completion", ["schema_version", "record_kind", "ceremony_id", "project_id", "accepted_control_event_id", "transition_id", "batch_id", "completion"]); return freezeRecord({ schema_version: expectLiteral(record.schema_version, 1, "completion marker version"), record_kind: expectLiteral(record.record_kind, "enrollment_transition_completion_marker", "completion marker kind"), ceremony_id: parseHc2DigestId("enrollment-ceremony", record.ceremony_id), project_id: parseEntityId("project", record.project_id), accepted_control_event_id: parseDigestId("control-event", record.accepted_control_event_id), transition_id: parseHc2DigestId("membership-transition", record.transition_id), batch_id: parseHc2DigestId("enrollment-batch", record.batch_id), completion: expectLiteral(record.completion, "verified_reopen_complete", "completion state") }); }

function parseDeliveries(value: unknown): readonly JournaledEpochDelivery[] { if (!Array.isArray(value) || value.length > 1024) throw new Error("Journaled deliveries must be bounded."); const result = value.map((entry) => { const record = expectExactRecord(entry, "journaled delivery", ["delivery_id", "exact_bytes"]); const bytes = expectBytes(record.exact_bytes, "journaled delivery bytes"); if (bytes.length === 0 || bytes.length > 4096) throw new Error("Journaled delivery bytes exceed the exact bound."); return freezeRecord({ delivery_id: parseHc2DigestId("epoch-delivery", record.delivery_id), exact_bytes: Uint8Array.from(bytes) }); }).sort((left, right) => left.delivery_id < right.delivery_id ? -1 : left.delivery_id > right.delivery_id ? 1 : 0); for (let index = 1; index < result.length; index += 1) if (result[index - 1].delivery_id === result[index].delivery_id) throw new Error("Journaled delivery IDs must be unique."); return Object.freeze(result); }
function validAdvance(from: EnrollmentTransitionPhase, to: EnrollmentTransitionPhase): boolean { return from === to || enrollmentTransitionPhases.indexOf(to) === enrollmentTransitionPhases.indexOf(from) + 1; }
function assertJournalMonotonic(current: EnrollmentTransitionJournal, next: EnrollmentTransitionJournal): void { if (current.wrapped_epoch && (!next.wrapped_epoch || !sameWrapped(current.wrapped_epoch, next.wrapped_epoch))) throw new Error("Wrapped epoch cannot be removed or replaced."); if (current.transition_id && current.transition_id !== next.transition_id) throw new Error("Transition identity cannot be replaced."); if (current.accepted_control_event_id && current.accepted_control_event_id !== next.accepted_control_event_id) throw new Error("Accepted control event cannot be replaced."); const byId = new Map(next.journaled_deliveries.map((entry) => [entry.delivery_id, entry])); for (const prior of current.journaled_deliveries) { const found = byId.get(prior.delivery_id); if (!found || !sameBytes(prior.exact_bytes, found.exact_bytes)) throw new Error("Journaled epoch delivery cannot be removed or replaced."); } if (current.batch_marker && (!next.batch_marker || current.batch_marker.batch_id !== next.batch_marker.batch_id)) throw new Error("Enrollment batch marker cannot be replaced."); }
function sameInvitation(left: StoredInvitation, right: StoredInvitation): boolean { return JSON.stringify(jsonSafe(left)) === JSON.stringify(jsonSafe(right)); }
function sameChallenge(left: StoredPossessionChallenge, right: StoredPossessionChallenge): boolean { return JSON.stringify(jsonSafe(left)) === JSON.stringify(jsonSafe(right)); }
function samePlan(left: EnrollmentTransitionJournal, right: EnrollmentTransitionJournal): boolean { return left.ceremony_id === right.ceremony_id && left.project_id === right.project_id && left.authorizing_device_id === right.authorizing_device_id && left.previous_control_head_id === right.previous_control_head_id && left.replacement_epoch_id === right.replacement_epoch_id && sameBytes(left.plan_sha256, right.plan_sha256); }
function sameCompletion(left: EnrollmentLocalCompletionMarker, right: EnrollmentLocalCompletionMarker): boolean { return left.ceremony_id === right.ceremony_id && left.project_id === right.project_id && left.accepted_control_event_id === right.accepted_control_event_id && left.transition_id === right.transition_id && left.batch_id === right.batch_id; }
function sameWrapped(left: WrappedLocalEpochRecord, right: WrappedLocalEpochRecord): boolean { return left.project_id === right.project_id && left.device_id === right.device_id && left.key_epoch_id === right.key_epoch_id && left.key_epoch_commitment === right.key_epoch_commitment && left.wrapping_key_generation === right.wrapping_key_generation && sameBytes(left.public_commitment_bytes, right.public_commitment_bytes) && sameBytes(left.nonce, right.nonce) && sameBytes(left.ciphertext, right.ciphertext); }
function jsonSafe(value: unknown): unknown { if (typeof value === "bigint") return value.toString(); if (value instanceof Uint8Array) return Array.from(value); if (Array.isArray(value)) return value.map(jsonSafe); if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key, child]) => [key, jsonSafe(child)])); return value; }
function exactDigest(value: unknown, label: string): Uint8Array { const bytes = expectBytes(value, label); if (bytes.length !== 32) throw new Error(`${label} must contain exactly 32 bytes.`); return Uint8Array.from(bytes); }
function safeProofId(value: unknown): string { if (typeof value !== "string") throw new Error("Possession proof ID is invalid."); return parseHc2DigestId("possession-proof", value); }
function invitationKey(projectId: ProjectId, invitationId: InvitationId): string { return `${parseEntityId("project", projectId)}\u0000${parseEntityId("invitation", invitationId)}`; }
function challengeKey(projectId: ProjectId, challengeId: string): string { return `${parseEntityId("project", projectId)}\u0000${parseHc2DigestId("possession-challenge", challengeId)}`; }
function ceremonyKey(projectId: ProjectId, ceremonyId: EnrollmentCeremonyId): string { return `${parseEntityId("project", projectId)}\u0000${parseHc2DigestId("enrollment-ceremony", ceremonyId)}`; }
function requiredValue<T>(value: T | null): T { if (value === null) throw new Error("Required stored value is absent."); return value; }
function sameBytes(left: Uint8Array, right: Uint8Array): boolean { if (left.length !== right.length) return false; let difference = 0; for (let index = 0; index < left.length; index += 1) difference |= left[index] ^ right[index]; return difference === 0; }
function strictTransaction(database: IDBDatabase, names: readonly string[], mode: IDBTransactionMode): IDBTransaction { return database.transaction([...names], mode, { durability: "strict" }); }
function requestValue<T>(request: IDBRequest<T>): Promise<T> { return new Promise((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error ?? new Error("IndexedDB request failed.")); }); }
function transactionDone(transaction: IDBTransaction): Promise<void> { return new Promise((resolve, reject) => { transaction.oncomplete = () => resolve(); transaction.onabort = transaction.onerror = () => reject(transaction.error ?? new Error("IndexedDB transaction failed.")); }); }
