import { parseEntityId, type AcknowledgementId, type DeviceId, type ProjectId } from "../identities.ts";
import { expectEnum, expectExactRecord, expectLiteral, expectUInt64, freezeRecord, type UInt64 } from "../validation.ts";
import { deriveEpochReceiptIdentity, parseEpochReceiptRecord, type EpochReceiptRecord } from "./enrollment-contracts.ts";
import { parseHc2DigestId, type EpochReceiptId } from "./identities.ts";

export type EpochReceiptReservation = Readonly<{
  schema_version: 1;
  record_kind: "epoch_receipt_sequence_reservation";
  project_id: ProjectId;
  device_id: DeviceId;
  acknowledgement_sequence: UInt64;
  previous_acknowledgement_id: AcknowledgementId | null;
  intended_receipt_id: EpochReceiptId;
  state: "pending" | "committed";
}>;

export interface Hc2EpochReceiptStore {
  reserve(value: EpochReceiptReservation): Promise<"reserved" | "exact_retry" | "conflict">;
  write(receipt: EpochReceiptRecord): Promise<"stored" | "exact_retry">;
  commit(receipt: EpochReceiptRecord): Promise<"committed" | "exact_retry">;
  ingest(receipt: EpochReceiptRecord): Promise<"stored" | "exact_retry">;
  list(projectId: ProjectId, deviceId: DeviceId): Promise<readonly EpochReceiptRecord[]>;
}

export class Hc2InMemoryEpochReceiptStore implements Hc2EpochReceiptStore {
  readonly #reservations = new Map<string, EpochReceiptReservation>(); readonly #receipts = new Map<string, EpochReceiptRecord>();
  async reserve(value: EpochReceiptReservation): Promise<"reserved" | "exact_retry" | "conflict"> { const reservation = parseEpochReceiptReservation(value); if (reservation.state !== "pending") throw new Error("New receipt reservation must be pending."); const key = reservationKey(reservation.project_id, reservation.device_id, reservation.acknowledgement_sequence); const existing = this.#reservations.get(key); if (existing) return sameReservation(existing, reservation) ? "exact_retry" : "conflict"; this.#reservations.set(key, reservation); return "reserved"; }
  async write(value: EpochReceiptRecord): Promise<"stored" | "exact_retry"> { const receipt = await verifiedReceipt(value); const key = receiptKey(receipt); const existing = this.#receipts.get(key); if (existing) { if (!sameReceipt(existing, receipt)) throw new Error("Conflicting bytes occupy the receipt identity."); return "exact_retry"; } this.#receipts.set(key, receipt); return "stored"; }
  async commit(value: EpochReceiptRecord): Promise<"committed" | "exact_retry"> { const receipt = await verifiedReceipt(value); const key = reservationKey(receipt.core.project_id, receipt.core.device_id, receipt.core.acknowledgement_sequence); const reservation = this.#reservations.get(key); if (!reservation || reservation.intended_receipt_id !== receipt.receipt_id || reservation.previous_acknowledgement_id !== receipt.core.previous_acknowledgement_id) throw new Error("Receipt sequence reservation CAS failed."); if (!this.#receipts.has(receiptKey(receipt))) throw new Error("Receipt must be stored before its reservation commits."); if (reservation.state === "committed") return "exact_retry"; this.#reservations.set(key, parseEpochReceiptReservation({ ...reservation, state: "committed" })); return "committed"; }
  async ingest(value: EpochReceiptRecord): Promise<"stored" | "exact_retry"> { return this.write(value); }
  async list(projectId: ProjectId, deviceId: DeviceId): Promise<readonly EpochReceiptRecord[]> { const project = parseEntityId("project", projectId); const device = parseEntityId("device", deviceId); return Object.freeze([...this.#receipts.values()].filter((entry) => entry.core.project_id === project && entry.core.device_id === device).sort(byReceipt)); }
}

const receiptDatabaseVersion = 1; const receiptStores = Object.freeze({ reservations: "epoch_receipt_reservations", receipts: "epoch_receipts" });
export const hc2EpochReceiptDatabaseSchema = Object.freeze({ version: receiptDatabaseVersion, stores: Object.freeze(Object.values(receiptStores).sort()) });

export class Hc2IndexedDbEpochReceiptStore implements Hc2EpochReceiptStore {
  readonly #factory: IDBFactory; readonly #name: string; #database: IDBDatabase | null = null;
  constructor(input: Readonly<{ indexed_db: IDBFactory; database_name: string }>) { if (!input?.indexed_db || typeof input.database_name !== "string" || !input.database_name || input.database_name.includes("\u0000")) throw new Error("Receipt IndexedDB requires an injected factory and explicit name."); this.#factory = input.indexed_db; this.#name = input.database_name; }
  async open(): Promise<void> { if (this.#database) return; this.#database = await new Promise<IDBDatabase>((resolve, reject) => { const request = this.#factory.open(this.#name, receiptDatabaseVersion); request.onupgradeneeded = () => { for (const name of Object.values(receiptStores)) if (!request.result.objectStoreNames.contains(name)) request.result.createObjectStore(name); }; request.onerror = () => reject(request.error ?? new Error("Receipt IndexedDB open failed.")); request.onsuccess = () => resolve(request.result); }); this.#database.onversionchange = () => this.close(); }
  close(): void { this.#database?.close(); this.#database = null; }
  async reserve(value: EpochReceiptReservation): Promise<"reserved" | "exact_retry" | "conflict"> { const reservation = parseEpochReceiptReservation(value); if (reservation.state !== "pending") throw new Error("New receipt reservation must be pending."); const transaction = strictTransaction(this.#require(), [receiptStores.reservations], "readwrite"); const store = transaction.objectStore(receiptStores.reservations); const key = reservationKey(reservation.project_id, reservation.device_id, reservation.acknowledgement_sequence); const raw = await requestValue<unknown>(store.get(key)); if (raw !== undefined) { const existing = parseEpochReceiptReservation(raw); await transactionDone(transaction); return sameReservation(existing, reservation) ? "exact_retry" : "conflict"; } store.add(reservation, key); await transactionDone(transaction); return "reserved"; }
  async write(value: EpochReceiptRecord): Promise<"stored" | "exact_retry"> { const receipt = await verifiedReceipt(value); const transaction = strictTransaction(this.#require(), [receiptStores.receipts], "readwrite"); const store = transaction.objectStore(receiptStores.receipts); const key = receiptKey(receipt); const raw = await requestValue<unknown>(store.get(key)); if (raw !== undefined) { if (!sameReceipt(parseEpochReceiptRecord(raw), receipt)) { transaction.abort(); throw new Error("Conflicting bytes occupy the receipt identity."); } await transactionDone(transaction); return "exact_retry"; } store.add(receipt, key); await transactionDone(transaction); return "stored"; }
  async commit(value: EpochReceiptRecord): Promise<"committed" | "exact_retry"> { const receipt = await verifiedReceipt(value); const transaction = strictTransaction(this.#require(), [receiptStores.reservations, receiptStores.receipts], "readwrite"); const reservationStore = transaction.objectStore(receiptStores.reservations); const key = reservationKey(receipt.core.project_id, receipt.core.device_id, receipt.core.acknowledgement_sequence); const raw = await requestValue<unknown>(reservationStore.get(key)); const storedReceipt = await requestValue<unknown>(transaction.objectStore(receiptStores.receipts).get(receiptKey(receipt))); if (raw === undefined || storedReceipt === undefined) { transaction.abort(); throw new Error("Receipt commit requires reservation and immutable receipt bytes."); } const reservation = parseEpochReceiptReservation(raw); if (reservation.intended_receipt_id !== receipt.receipt_id || reservation.previous_acknowledgement_id !== receipt.core.previous_acknowledgement_id) { transaction.abort(); throw new Error("Receipt sequence reservation CAS failed."); } if (reservation.state === "committed") { await transactionDone(transaction); return "exact_retry"; } reservationStore.put(parseEpochReceiptReservation({ ...reservation, state: "committed" }), key); await transactionDone(transaction); return "committed"; }
  async ingest(value: EpochReceiptRecord): Promise<"stored" | "exact_retry"> { return this.write(value); }
  async list(projectId: ProjectId, deviceId: DeviceId): Promise<readonly EpochReceiptRecord[]> { const project = parseEntityId("project", projectId); const device = parseEntityId("device", deviceId); const transaction = strictTransaction(this.#require(), [receiptStores.receipts], "readonly"); const values = await requestValue<unknown[]>(transaction.objectStore(receiptStores.receipts).getAll()); await transactionDone(transaction); return Object.freeze(values.map(parseEpochReceiptRecord).filter((entry) => entry.core.project_id === project && entry.core.device_id === device).sort(byReceipt)); }
  #require(): IDBDatabase { if (!this.#database) throw new Error("Receipt IndexedDB must be opened explicitly."); return this.#database; }
}

export function parseEpochReceiptReservation(value: unknown): EpochReceiptReservation { const record = expectExactRecord(value, "epoch receipt reservation", ["schema_version", "record_kind", "project_id", "device_id", "acknowledgement_sequence", "previous_acknowledgement_id", "intended_receipt_id", "state"]); const sequence = expectUInt64(record.acknowledgement_sequence, "receipt reservation sequence"); const previous = record.previous_acknowledgement_id === null ? null : parseAcknowledgement(record.previous_acknowledgement_id); if ((sequence === BigInt(0)) !== (previous === null)) throw new Error("Receipt reservation predecessor semantics are invalid."); return freezeRecord({ schema_version: expectLiteral(record.schema_version, 1, "receipt reservation version"), record_kind: expectLiteral(record.record_kind, "epoch_receipt_sequence_reservation", "receipt reservation kind"), project_id: parseEntityId("project", record.project_id), device_id: parseEntityId("device", record.device_id), acknowledgement_sequence: sequence, previous_acknowledgement_id: previous, intended_receipt_id: parseHc2DigestId("epoch-receipt", record.intended_receipt_id), state: expectEnum(record.state, ["pending", "committed"] as const, "receipt reservation state") }); }
async function verifiedReceipt(value: EpochReceiptRecord): Promise<EpochReceiptRecord> { const receipt = parseEpochReceiptRecord(value); const identity = await deriveEpochReceiptIdentity(receipt.core); if (identity.id !== receipt.receipt_id) throw new Error("Epoch receipt identity mismatch."); return receipt; }
function parseAcknowledgement(value: unknown): AcknowledgementId { if (typeof value !== "string" || !/^pm:acknowledgement:v1:[a-z2-7]{52}$/.test(value)) throw new Error("Receipt acknowledgement predecessor is invalid."); return value as AcknowledgementId; }
function reservationKey(projectId: ProjectId, deviceId: DeviceId, sequence: UInt64): string { return `${parseEntityId("project", projectId)}\u0000${parseEntityId("device", deviceId)}\u0000${expectUInt64(sequence, "receipt sequence").toString().padStart(20, "0")}`; }
function receiptKey(receipt: EpochReceiptRecord): string { return `${reservationKey(receipt.core.project_id, receipt.core.device_id, receipt.core.acknowledgement_sequence)}\u0000${receipt.receipt_id}`; }
function sameReservation(left: EpochReceiptReservation, right: EpochReceiptReservation): boolean { return left.project_id === right.project_id && left.device_id === right.device_id && left.acknowledgement_sequence === right.acknowledgement_sequence && left.previous_acknowledgement_id === right.previous_acknowledgement_id && left.intended_receipt_id === right.intended_receipt_id; }
function sameReceipt(left: EpochReceiptRecord, right: EpochReceiptRecord): boolean { return left.receipt_id === right.receipt_id && left.signature_bytes.length === right.signature_bytes.length && left.signature_bytes.every((value, index) => value === right.signature_bytes[index]); }
function byReceipt(left: EpochReceiptRecord, right: EpochReceiptRecord): number { return left.core.acknowledgement_sequence < right.core.acknowledgement_sequence ? -1 : left.core.acknowledgement_sequence > right.core.acknowledgement_sequence ? 1 : left.receipt_id < right.receipt_id ? -1 : 1; }
function strictTransaction(database: IDBDatabase, names: readonly string[], mode: IDBTransactionMode): IDBTransaction { return database.transaction([...names], mode, { durability: "strict" }); }
function requestValue<T>(request: IDBRequest<T>): Promise<T> { return new Promise((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error ?? new Error("IndexedDB request failed.")); }); }
function transactionDone(transaction: IDBTransaction): Promise<void> { return new Promise((resolve, reject) => { transaction.oncomplete = () => resolve(); transaction.onabort = transaction.onerror = () => reject(transaction.error ?? new Error("IndexedDB transaction failed.")); }); }
